[project]
name = "openai-sdlc-slackbot"
requires-python = ">=3.8"
version = "1.0.0"
dependencies = [
    "toml",
    "openai_slackbot @ file://$REPO_ROOT/shared/openai-slackbot",
    "validators",
    "google-auth",
    "google-auth-httplib2",
    "google-auth-oauthlib",
    "google-api-python-client",
    "psycopg",
    "psycopg2-binary",
    "peewee",
]

[build-system]
requires = ["setuptools>=64.0"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
asyncio_mode = "auto"
env = [
  "SLACK_BOT_TOKEN=mock-token",
  "SOCKET_APP_TOKEN=mock-token",
  "OPENAI_API_KEY=mock-key",
]
